# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'codecamp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for codecamp
  pod 'AppCenter/Crashes', '~> 1.7.1'
  pod 'AppCenter/Analytics', '~> 1.7.1'
  pod 'AppCenterReactNativeShared', '~> 1.6.0'


  

  platform :ios, '9.0'
  target 'codecampTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'codecamp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for codecamp-tvOS

  target 'codecamp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
